docker pull mcr.microsoft.com/windows/servercore:1909
docker pull mcr.microsoft.com/windows/servercore:ltsc2019
docker pull mcr.microsoft.com/powershell
docker pull mcr.microsoft.com/windows:1909
docker pull mcr.microsoft.com/windows/nanoserver:1909
docker pull mcr.microsoft.com/windows/servercore/iis:windowsservercore-1909
docker pull portainer/portainer
docker pull portainer/agent
docker pull stefanscherer/dockertls-windows